micronaut:
  application:
    name: clienteService
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123456'
    dialect: POSTGRES

---
jpa:
  default:
    packages-to-scan:
      - 'br.com.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true